CREATE TABLE staging_sales (
    category TEXT,
    city TEXT,
    country TEXT,
    customer_id TEXT,
    customer_name TEXT,
    discount NUMERIC(4, 2),
    market TEXT,
    order_date DATE,
    order_id TEXT,
    order_priority TEXT,
    product_id TEXT,
    product_name TEXT,
    profit NUMERIC(10, 2),
    quantity INT,
    region TEXT,
    row_id INT PRIMARY KEY,
    sales NUMERIC(10, 2),
    segment TEXT,
    ship_date DATE,
    ship_mode TEXT,
    shipping_cost NUMERIC(10, 2),
    state TEXT,
    sub_category TEXT,
    market_region TEXT
);
